/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryRequest = IDL.Record({
  'region' : IDL.Text,
  'category' : IDL.Text,
});
export const InflationSeries = IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64));

export const idlService = IDL.Service({
  'getInflationData' : IDL.Func([CategoryRequest], [InflationSeries], []),
  'getRegionalCategories' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
  'getTopInflationSubcategories' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryRequest = IDL.Record({
    'region' : IDL.Text,
    'category' : IDL.Text,
  });
  const InflationSeries = IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64));
  
  return IDL.Service({
    'getInflationData' : IDL.Func([CategoryRequest], [InflationSeries], []),
    'getRegionalCategories' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], []),
    'getTopInflationSubcategories' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };